# Generated by Django 4.1.2 on 2022-10-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='activitysession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activitysession',
            name='time',
        ),
        migrations.AddField(
            model_name='activitysession',
            name='day',
            field=models.TextField(choices=[('lun', 'Lundi'), ('mar', 'Mardi'), ('mer', 'Mercredi'), ('jeu', 'Jeudi'), ('ven', 'Vendredi'), ('san', 'Samedi'), ('dim', 'Dimanche')], default='lun'),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='end_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
