# Generated by Django 4.1.2 on 2022-10-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitytype_remove_activitysession_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activitysession',
            name='session_age_range',
            field=models.CharField(default='Tous les âges', max_length=200),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='session_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
