# Generated by Django 4.1.2 on 2022-10-24 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype'),
        ),
        migrations.AddField(
            model_name='activityprice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityprice',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
